config/routes.rb
Rails.application.routes.draw do

	root 'restaurants#index'

  resources :restaurants, only: [:index, :show] do
    resources :reservations
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :restaurants
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  validates :date, :hour, :party_size, presence: true

  validate :has_enough_seats

  def has_enough_seats
    if !restaurant.available?(party_size, date, hour)
  	 errors.add(:party_size, "is too big to accommodate at that time")
    end
  end

  belongs_to :restaurant
  belongs_to :user

  # def availability
  # 	if restaurant.available?(party_size, date, hour)
  # 		errors.add(:base, "Restaurant is full at this time")
  # 	end
  # end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :address, :city, presence: true

  has_many :reservations
  has_many :users, through: :reservations

  def self.search(search)
    if search
      where("LOWER(name) LIKE ? OR LOWER(cuisine) LIKE ?", "%#{search.downcase}%", "%#{search.downcase}%")
    else
      self.all
    end
  end

  def time_options
    (9..22).map do |hour|
      ampm, twelve_hour = hour.divmod(12)
      twelve_hour = 12 if twelve_hour == 0
      text = "#{twelve_hour} #{ampm == 0 ? "am" : "pm"}"
      [text, hour]
    end
  end

  def available?(party_size, date, hour)
    party_size = party_size.to_i
    hour = hour.to_i
    
    reserved = reservations.where(:hour => hour, :date => date).sum(:party_size)
    availability = capacity - reserved

    p size: party_size, hour: hour, date: date, reserved: reserved, cap: capacity, availability: availability
    
    party_size <= availability
  end




end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :email, presence: true

  has_many :reservations
  has_many :restaurants, through: :reservations
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

  before_action :authorize
  
  private
  def authorize
    unless current_user.admin == true
      flash[:notice] = "Unauthorized!"
      redirect_to "/"
    end
  end
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < Admin::ApplicationController

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::ApplicationController
  
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to admin_restaurants_url
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to admin_restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:address, :city, :name, :phone_number, :menu_url, :picture_url, :capacity, :cuisine)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # before_filter :load_restaurant

  # TODO: Discuss permissions of user to see if a user can delete or edit a reservation

  def index
    @reservations = Reservation.where(:user_id => current_user.id)
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    # if @restaurant.available?(reservation_params[:party_size], reservation_params[:date], reservation_params[:hour])
    @reservation = @restaurant.reservations.new(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      redirect_to restaurant_reservation_path(@restaurant, @reservation)
    else
      render "restaurants/show"
      # redirect_to restaurant_path(@restaurant)
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @restaurant = @reservation.restaurant
  end

  def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update_attributes(reservation_params)
      redirect_to restaurant_reservation_path(@reservation.restaurant, @reservation)
    else
      render :edit_restaurant_reservation
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to :restaurant_reservations
  end

  private
  
  def reservation_params
    params.require(:reservation).permit(:date, :hour, :party_size, :restaurant_id)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  # Within scope of user.... 
  # Only want them to see all restaurants and show a particular restaurant

  def index
    @restaurants = Restaurant.search(params[:search]) 
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to restaurants_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cuisine %><br />
    <%= f.text_field :cuisine %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :menu_url %><br />
    <%= f.text_field :menu_url %>
  </div>
   <div class="field">
    <%= f.label :picture_url %><br />
    <%= f.text_field :picture_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/restaurants/edit.html.erb
<h1>Editing Resaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_restaurants_path %>

app/views/admin/restaurants/index.html.erb
<h2>Restaurants</h2>

<div class="restaurants">

<% @restaurants.each do |restaurant| %>
  <p><%= link_to image_tag(restaurant.picture_url), restaurant_path(restaurant) %> </p>
  <p><%= restaurant.name %> </p>
  <p><%= restaurant.city %></p>
<% end %>
</a>

</div>

app/views/admin/restaurants/new.html.erb
<h1>New Resaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_restaurants_path %>

app/views/admin/restaurants/show.html.erb
<h3><%= @restaurant.name %></h3>

<img src="<%= @restaurant.picture_url %>" alt="<%= @restaurant.name %>" width="20%">
<p>Type: <%= @restaurant.cuisine %></p>
<p>City: <%= @restaurant.city %></p>
<p>address: <%= @restaurant.address %></p>
<p>Phone Number: <%= @restaurant.phone_number %></p>
<p>Capacity: <%= @restaurant.capacity %></p>
<% if @restaurant.menu_url? %>
  <p>Menu URL: <a href="<%= @restaurant.menu_url %>">View Menu</a></p>
<% end %>

app/views/layouts/_form.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=" / ">Seat YoSelf</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
        <%= form_tag restaurants_path, :method => 'get' do %>
		    <%= text_field_tag :search, params[:search] %>
        <button type="submit" class="btn btn-default">Submit</button>
        <% end %>
      </form>
      	</div>   	
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "My Reservations", restaurant_reservations_path("current") %></li>
            <li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
          </ul>
      <% else %>
          <li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Log in", new_session_path %> </li></button>
          <li>&nbsp</li>
          <li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign up", new_user_path %></li></button>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seat Yoself!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="assets/style.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body class="<%= controller_name %> <%= action_name %>">



  <%= render 'layouts/form' %>
  <br>
  <br>
  <br>

  <div class="container">

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert" id="notice"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert" id="alert"><%= flash[:alert] %></div>
  <% end %>

  <%= yield %>

</div>


</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for([@restaurant, @reservation]) do |f| %>
	<% if @reservation.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being made:</h2>
	    <ul>
	    <% @reservation.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>

	<div class="field">
		<%= f.label :date %><br>
		<%= f.date_field :date %>
		
		<%= f.label :hour %>
		<%= f.select :hour, @restaurant.time_options %>
	</div>

	<div class="field">
	  <%= f.label :party_size %><br>
	  <%= f.number_field(:party_size, {in: 1.0..50.0, step: 1}) %>
	</div>

	<div class="actions">
	  <%= f.submit %>
	</div>
<% end %>

app/views/reservations/edit.html.erb
<h2>Edit Your Reservation</h2>
<%= render "reservations/form" %>

app/views/reservations/index.html.erb
<ul>

<% @reservations.each do |reservation| %>
	<li>
		<% if reservation.restaurant %>
			<%= link_to reservation.restaurant.name, restaurant_reservation_path(reservation.restaurant, reservation) %>
		<% end %>
		<%= link_to "Edit Reservation", edit_restaurant_reservation_path(reservation.restaurant, reservation) %>
		|
		<%= link_to 'Destroy', [reservation.restaurant, reservation], method: :delete, data: { confirm: 'Are you sure?' } %>
		<br>
		Date: <%= reservation.date %>
		<br>
		Time: <%= reservation.hour %>
		<br>
		Party of: <%= reservation.party_size %>
	</li>
<% end %>

</ul>

app/views/reservations/show.html.erb
<h2>Reservation Info for <%= @reservation.user.name %> </h2>

<div>
	<p><%= link_to image_tag(@reservation.restaurant.picture_url)%> </p>
	<p>Reservation for <%= @reservation.date %>, <%= @reservation.hour %>:00</p>
	<p>Party Size: <%= @reservation.party_size %></p>
	<p>Restaurant Name: <%= @reservation.restaurant.name %></p>
</div>

<div>
	<p>
	<%= link_to "Edit Reservation", edit_restaurant_reservation_path %>
	|
	<%= link_to 'Destroy', [@reservation.restaurant, @reservation], method: :delete, data: { confirm: 'Are you sure?' } %>
	</p>

</div>

<h3>Use this number to help us verify you once you reach our restaurant: <%= @reservation.id %>3123</h3>

app/views/restaurants/index.html.erb
<Legend>Restaurants</legend>

<% @restaurants.each do |restaurant| %>

<div class="row">
<div class="col-md-7">
        <img class="img-responsive" src="<%= restaurant.picture_url %>" alt="">
    </a>
</div>
<div class="col-md-5">
    <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
    <h4><%= restaurant.city %></h4>
</div>
</div>

<% end %>
<!-- 
<div class="restaurants">

<% @restaurants.each do |restaurant| %>
	<p><%= link_to image_tag(restaurant.picture_url), restaurant_path(restaurant) %> </p>
	<p><%= restaurant.name %> </p>
	<p><%= restaurant.city %></p>
<% end %>
</a>

</div>
 -->

app/views/restaurants/show.html.erb
<h3><%= @restaurant.name %></h3>
<table><tr><td>

<img src="<%= @restaurant.picture_url %>" alt="<%= @restaurant.name %>" width="20%">
<p>Type: <%= @restaurant.cuisine %></p>
<p>City: <%= @restaurant.city %></p>
<p>address: <%= @restaurant.address %></p>
<p>Phone Number: <%= @restaurant.phone_number %></p>
<p>Capacity: <%= @restaurant.capacity %></p>
<% if @restaurant.menu_url? %>
  <p>Menu URL: <a href="<%= @restaurant.menu_url %>">View Menu</a></p>
<% end %>

</td>

<td>

<% if current_user %>
  <h4>New Reservation</h4>

  <%= render "reservations/form" %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to make a reservation.</p> 
<% end %>

</td></tr></table>

app/views/users/new.html.erb
 <Legend>Create a New User</legend>

<%= form_for(@user) do |f| %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
  
<% end %>